project_id = "wvmrmapnzdixesfasivs"

[functions.get-event-participants]
verify_jwt = false

[functions.checkin-participant]
verify_jwt = false

[functions.submit-selections]
verify_jwt = false

[functions.send-match-emails]
verify_jwt = true

[functions.send-reminder-email]
verify_jwt = true

[functions.send-scheduled-emails]
verify_jwt = false
